<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Albacore.ViVeTool</RootNamespace>
    <AssemblyName>ViVeTool</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ViVe\ViVe.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Extra\FeatureDictionary.pfs">
      <Link>FeatureDictionary.pfs</Link>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>
</Project>
